print("==========================")
print("CALCULADORA - BHASKÁRA 1.0")
print("==========================")
print("")
a = int(input("Digite o valor de A: "))
b = int(input("Agora, digite o valor de B: "))
c = int(input("Por fim, digite o valor de C: "))
print("")
print("======================")
print("A equação digitada é:")
print(a, "X²", b, "X",c, " = 0")
print("======================")
#raízes da equação:
delta = ((b**2)-(4*a*c))
x1 = ((-b + (delta**(1/2)))/(2*a))
x2 = ((-b - (delta**(1/2)))/(2*a))
#fim do corpo-calculador.
print("")
print("..........................")
print("O valor de DELTA é: ", delta,".")
print("..........................")
print("")
print("---------------------------")
print("As raízes da equação são: ")
print("X¹ =", x1, "e X² =", x2)
print("---------------------------")
print("")
print("****************************")
enter = input("Click ENTER para finalizar...")
print("****************************")
