def grade():
    print("+ - - - - + - - - - +")
    print("|         |         |")
    print("|         |         |")
    print("|         |         |")
    print("|         |         |")
    print("+ - - - - + - - - - +")
    print("|         |         |")
    print("|         |         |")
    print("|         |         |")
    print("|         |         |")
    print("+ - - - - + - - - - +")
grade()
